src/TestSite/Controllers/QuickCms/EntityController.cs
using System;
using System.Linq;
using System.Reflection;
using Microsoft.AspNet.Mvc;
using QuickCms;
using TestSite.Models;

namespace TestSite.Controllers.QuickCms
{
    public class EntityController : Controller
    {
        private readonly IRepositoryFactory _repoFac;
        private readonly IModelBuilder _modelBuilder;

        public EntityController(IRepositoryFactory repoFac, IModelBuilder modelBuilder)
        {
            _repoFac = repoFac;
            _modelBuilder = modelBuilder;
        }

        public IActionResult Index(string entityName)
        {
            using (var repo = _repoFac.CreateRepository(entityName))
            {
                var model = new EntityIndexViewModel
                {
                    EntityName = entityName,
                    Entities = repo.GetAll().Cast<object>()
                        .Select(item => _modelBuilder.GetModel(item))
                        .ToList()
                };

                return View(model);
            }
        }

        [HttpGet]
        public IActionResult Create(string entityName)
        {
            using (var repo = _repoFac.CreateRepository(entityName))
            {
                var entityType = ((IRepositoryMetadata) repo).GetEntityType();
                var model = _modelBuilder.GetModel(Activator.CreateInstance(entityType));

                return View("Edit", model);
            }
        }

        [HttpGet]
        public IActionResult Edit(string entityName, object id)
        {
            using (var repo = _repoFac.CreateRepository(entityName))
            {
                var model = _modelBuilder.GetModel(repo.Get(id));

                return View(model);
            }
        }

        [HttpPost]
        public IActionResult Edit(ItemModel model)
        {
            if (ModelState.IsValid)
            {
                using (var repo = _repoFac.CreateRepository(model.TypeName))
                {
                    repo.Save(model.Item);
                }

                return RedirectToAction("Index", new { entityName = model.TypeName });
            }

            return View(model);
        }

        public IActionResult Delete(string entityName, object id)
        {
            using (var repo = _repoFac.CreateRepository(entityName))
            {
                repo.Delete(id);
            }

            return RedirectToAction("Index", new { entityName });
        }
    }
}

src/TestSite/Views/Entity/Edit.cshtml
@model QuickCms.ItemModel
@{
    Layout = "/Views/Shared/_QuickCmsLayout.cshtml";
}

<h1>Edit @Model.TypeName</h1>
@using (Html.BeginForm("Edit", "Entity"))
{
    @Html.EditorFor(m => m.Item)
    @Html.HiddenFor(m => m.TypeName)
    @Html.HiddenFor(m => m.FullTypeName)
    <input type="submit" value="Save" />
}

src/TestSite/Views/Entity/Index.cshtml
@model TestSite.Models.EntityIndexViewModel
@{
    Layout = "/Views/Shared/_QuickCmsLayout.cshtml";
}

<h1>@(Model.EntityName)s</h1>
@Html.ActionLink("New", "Create", new { Model.EntityName })
<ul>
    @foreach (var entity in Model.Entities)
    {
        <li>
            @Html.ActionLink(entity.Name, "Edit", new { Model.EntityName, entity.Id })
            [@Html.ActionLink("x", "Delete", new { Model.EntityName, entity.Id })]
        </li>
    }
</ul>